"""
Mammo-CLIP downstream classifier finetuning.
"""

import argparse
import os
import pickle
import warnings
from pathlib import Path

import pandas as pd
import torch

from Classifiers.experiments import do_experiments
from utils import get_Paths, seed_all

warnings.filterwarnings("ignore")


def config():
    parser = argparse.ArgumentParser(description="Mammo-CLIP Downstream Finetuning")

    parser.add_argument("--tensorboard-path", metavar="DIR", default="./logs", help="path to tensorboard logs")
    parser.add_argument("--checkpoints", metavar="DIR", default="./checkpoints", help="path to checkpoints")
    parser.add_argument("--output_path", metavar="DIR", default="./outputs", help="path to output logs")
    parser.add_argument("--data-dir", default="G:/data", type=str, help="Path to data directory")
    parser.add_argument("--img-dir", default="images", type=str, help="Relative path from data-dir to image directory")

    parser.add_argument("--clip_chk_pt_path", default="./model/b5-model-best-epoch-7.tar", type=str, help="Path to Mammo-CLIP checkpoint")
    parser.add_argument("--csv-file", default="train_with_test_folds.csv", type=str, help="CSV file generated by prepare_folds.py")
    parser.add_argument("--dataset", default="custom", type=str, help="Dataset name")
    parser.add_argument("--data_frac", default=1.0, type=float, help="Fraction of training data to use")

    parser.add_argument(
        "--arch",
        default="breast_clip_det_b5_period_n_ft",
        type=str,
        help="Architecture: breast_clip_det_b5_period_n_ft or breast_clip_det_b5_period_n_lp",
    )
    parser.add_argument("--label", default="cancer", type=str, help="Label column name in CSV")
    parser.add_argument("--detector-threshold", default=0.1, type=float)
    parser.add_argument("--swin_encoder", default="microsoft/swin-tiny-patch4-window7-224", type=str)
    parser.add_argument("--pretrained_swin_encoder", default="y", type=str)
    parser.add_argument("--swin_model_type", default="y", type=str)
    parser.add_argument("--VER", default="084", type=str)

    parser.add_argument("--epochs-warmup", default=0, type=float)
    parser.add_argument("--num_cycles", default=0.5, type=float)
    parser.add_argument("--alpha", default=10, type=float)
    parser.add_argument("--sigma", default=15, type=float)
    parser.add_argument("--p", default=1.0, type=float)
    parser.add_argument("--mean", default=0.3089279, type=float)
    parser.add_argument("--std", default=0.25053555408335154, type=float)
    parser.add_argument("--focal-alpha", default=0.6, type=float)
    parser.add_argument("--focal-gamma", default=2.0, type=float)
    parser.add_argument("--num-classes", default=1, type=int)

    parser.add_argument("--n_folds", default=5, type=int, help="Number of cross-validation folds")
    parser.add_argument("--start-fold", default=0, type=int)
    parser.add_argument("--seed", default=42, type=int)
    parser.add_argument("--batch-size", default=8, type=int)
    parser.add_argument("--num-workers", default=4, type=int)
    parser.add_argument("--epochs", default=30, type=int)
    parser.add_argument("--lr", default=5.0e-5, type=float)
    parser.add_argument("--weight-decay", default=1e-4, type=float)
    parser.add_argument("--warmup-epochs", default=1, type=float)
    parser.add_argument("--img-size", nargs="+", default=[912, 1520], type=int, help="Image size [width, height]")
    parser.add_argument("--device", default="cuda", type=str)
    parser.add_argument("--apex", default="y", type=str)
    parser.add_argument("--print-freq", default=5000, type=int)
    parser.add_argument("--log-freq", default=1000, type=int)
    parser.add_argument("--running-interactive", default="n", type=str)
    parser.add_argument("--inference-mode", default="n", type=str, help="Set to 'y' for inference only")
    parser.add_argument("--model-type", default="classifier", type=str)
    parser.add_argument("--weighted-BCE", default="n", type=str, help="Use weighted BCE loss (y/n)")
    parser.add_argument("--patience", default=10, type=int, help="Early stopping patience (0=disabled)")
    parser.add_argument("--balanced-dataloader", default="n", type=str, help="Use balanced dataloader (y/n)")

    return parser.parse_args()


def main(args):
    seed_all(args.seed)
    device = "cuda" if torch.cuda.is_available() else "cpu"

    args.root = f"lr_{args.lr}_epochs_{args.epochs}_weighted_BCE_{args.weighted_BCE}_{args.label}_data_frac_{args.data_frac}"
    args.apex = args.apex == "y"
    args.pretrained_swin_encoder = args.pretrained_swin_encoder == "y"
    args.swin_model_type = args.swin_model_type == "y"
    args.running_interactive = args.running_interactive == "y"

    chk_pt_path, output_path, tb_logs_path = get_Paths(args)
    args.chk_pt_path = chk_pt_path
    args.output_path = output_path
    args.tb_logs_path = tb_logs_path

    os.makedirs(chk_pt_path, exist_ok=True)
    os.makedirs(output_path, exist_ok=True)
    os.makedirs(tb_logs_path, exist_ok=True)
    print("====================> Paths <====================")
    print(f"checkpoint_path: {chk_pt_path}")
    print(f"output_path: {output_path}")
    print(f"tb_logs_path: {tb_logs_path}")
    print(f"data_dir: {args.data_dir}")
    print(f"img_dir: {args.img_dir}")
    print(f"csv_file: {args.csv_file}")
    print(f"clip_checkpoint: {args.clip_chk_pt_path}")
    print("device:", device)
    print("torch version:", torch.__version__)
    print("====================> Paths <====================")

    pickle.dump(args, open(os.path.join(output_path, f"seed_{args.seed}_train_configs.pkl"), "wb"))
    torch.cuda.empty_cache()

    if args.weighted_BCE == "y":
        csv_path = Path(args.csv_file)
        if not csv_path.is_absolute():
            csv_path = Path(args.data_dir) / csv_path
        df = pd.read_csv(csv_path)
        train_df = df[df["fold"] >= 0]
        args.BCE_weights = {}
        if args.n_folds == 0:
            n_neg = (train_df[args.label] == 0).sum()
            n_pos = (train_df[args.label] == 1).sum()
            args.BCE_weights["fold0"] = n_neg / max(n_pos, 1)
        else:
            for fold in range(args.n_folds):
                fold_train = train_df[train_df["fold"] != fold]
                n_neg = (fold_train[args.label] == 0).sum()
                n_pos = (fold_train[args.label] == 1).sum()
                args.BCE_weights[f"fold{fold}"] = n_neg / max(n_pos, 1)
        print(f"Auto-computed BCE weights: {args.BCE_weights}")

    do_experiments(args, device)


if __name__ == "__main__":
    args = config()
    main(args)
